{% set name = "hub-sdk" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hub-sdk-{{ version }}.tar.gz
  sha256: 9e35154874824bf4280db76b5ca99f0aeb1c9846e404f567c5e7dc737a1f696c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=43.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - requests

test:
  imports:
    - hub_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.ultralytics.com/hub/sdk/
  summary: Ultralytics HUB Client SDK.
  dev_url: https://github.com/ultralytics/hub-sdk/
  license: AGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - glenn-jocher